### ISSUE TITLE
file-format.txt should describe LMFDB_LABEL and LMFDB_NCURVE

### ISSUE THREAD

**Issue by pdehaye** [JohnCremona/ecdata#3]
Or at least where their definition can be found.

**Comment by JohnCremona** [comment]
See https://github.com/LMFDB/lmfdb-inventory/blob/master/db-elliptic_curves.md for a current description.   

It is not good but there are 3 different places where this information is given.  The file here (file_format.txt) is rather old and was written when this data first came under revision control and (at the same time) was first put into the LMFDB.  Secondly, in the upload script file for the lmfdb: https://github.com/LMFDB/lmfdb/blob/master/lmfdb/elliptic_curves/import_ec_data.py .  And thirdly, new file in lmfdb-inventory.

While these do all exist they should of course be consistent, and I will duly update file_format.txt.

**Comment by JohnCremona** [comment]
I have updated file_format.txt, included a description of the 2adic files, corrected some errors and made it more explicit about the types of data involved.
