### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by SnarkBoojum** [JohnCremona/ecdata#5]
Just a friendly reminder before you tag the next release :-P

**Comment by JohnCremona** [comment]
Not forgotten, and in progress.  Note that the files in growth/ were supplied by Enrique Gonzalez-Jimenez and those in galrep/ by Andrew Sutherland, whose permission would be required.  Also scripts/2adic.m was written by Jeremy Rouse and used for the data in 2adic/.
As far as I know I would only need permissions from people who supplied me with code in the repo or with data files in the repo.

**Comment by SnarkBoojum** [comment]
Well, in Debian we tend to be quite serious with copyright matters ; see for example for [sagemath](https://salsa.debian.org/science-team/sagemath/blob/master/debian/copyright)... So yes, having some precise copyright assignments and definite licenses on the various files is important.

**Comment by JohnCremona** [comment]
Not forgotten, just waiting a response from Magma.

**Comment by SnarkBoojum** [comment]
Still waiting for an answer?

**Comment by JohnCremona** [comment]
Yes.

**Comment by SnarkBoojum** [comment]
Is it usual that they're that long to answer? Can their contribution be dropped/replaced if it's obvious they disagree?

**Comment by JohnCremona** [comment]
There is now a LICENSE file.
